"""status

Revision ID: 031708b8fd1b
Revises: 856454f9fe07
Create Date: 2025-05-27 14:20:06.324123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '031708b8fd1b'
down_revision: Union[str, None] = '856454f9fe07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_content', sa.Column('is_sent', sa.Boolean(), default=False))
    op.add_column('email_content', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_content', 'status')
    op.drop_column('email_content', 'is_sent')
    # ### end Alembic commands ###
