"""scheduled table update

Revision ID: 06ce5e405074
Revises: 8e845f4ad3e1
Create Date: 2025-07-25 11:27:58.419166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06ce5e405074'
down_revision: Union[str, None] = '8e845f4ad3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_content', sa.Column('media_type', sa.String(), nullable=False))
    op.add_column('scheduled_content', sa.Column('media_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_content', 'media_id')
    op.drop_column('scheduled_content', 'media_type')
    # ### end Alembic commands ###
