"""smart chatbot

Revision ID: 08be3e49b751
Revises: 5758f3f5ba84
Create Date: 2025-10-08 14:57:13.190353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08be3e49b751'
down_revision: Union[str, None] = '5758f3f5ba84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_customer_support_chatbot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bot_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('transfer_case', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_file', sa.String(), nullable=True),
    sa.Column('reference_text', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smart_agent_integration',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('selected_avatar_url', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('domain', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['smart_customer_support_chatbot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smart_agent_integration')
    op.drop_table('smart_customer_support_chatbot')
    # ### end Alembic commands ###
