"""update time

Revision ID: 0df21e7bd75b
Revises: 561eac665ae3
Create Date: 2025-11-05 07:50:04.258940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0df21e7bd75b'
down_revision: Union[str, None] = '561eac665ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_customer_support_chatbot', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('smart_customer_support_chatbot', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smart_customer_support_chatbot', 'updated_at')
    op.drop_column('smart_customer_support_chatbot', 'created_at')
    # ### end Alembic commands ###
