"""adding credits

Revision ID: 11fac032b4db
Revises: 32714aafd114
Create Date: 2025-05-26 12:01:22.151618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11fac032b4db'
down_revision: Union[str, None] = '32714aafd114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('credits', sa.Integer(), default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'credits')
    # ### end Alembic commands ###
