"""youtube model

Revision ID: 16597323a6ba
Revises: 82a0208d5686
Create Date: 2025-07-21 09:16:43.049495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16597323a6ba'
down_revision: Union[str, None] = '82a0208d5686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_content', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('custom_instructions', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_script_id'), 'youtube_script', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_script_id'), table_name='youtube_script')
    op.drop_table('youtube_script')
    # ### end Alembic commands ###
