"""phone_agent

Revision ID: 23d27a6b6542
Revises: 3ea69336c167
Create Date: 2025-06-03 11:29:59.002082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23d27a6b6542'
down_revision: Union[str, None] = '3ea69336c167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_agent_phone_numbers_id'), 'agent_phone_numbers', ['id'], unique=False)
    op.create_table('phone_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('voice', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_agent_id'), 'phone_agent', ['id'], unique=False)
    op.create_table('phone_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('voice', sa.String(), nullable=False),
    sa.Column('choose_calendar', sa.String(), nullable=True),
    sa.Column('max_call_time', sa.Integer(), nullable=True),
    sa.Column('target_lists', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('agent', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent'], ['phone_agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_campaign_id'), 'phone_campaign', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_campaign_id'), table_name='phone_campaign')
    op.drop_table('phone_campaign')
    op.drop_index(op.f('ix_phone_agent_id'), table_name='phone_agent')
    op.drop_table('phone_agent')
    op.drop_index(op.f('ix_agent_phone_numbers_id'), table_name='agent_phone_numbers')
    op.drop_table('agent_phone_numbers')
    # ### end Alembic commands ###
