"""update user and tema table

Revision ID: 29e8740b9acb
Revises: 3bd2d5f6cd6d
Create Date: 2025-08-07 09:33:49.416040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29e8740b9acb'
down_revision: Union[str, None] = '3bd2d5f6cd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('creditRenewDate', sa.Date(), nullable=True))
    op.add_column('team', sa.Column('numberOfRenewMonths', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('nextMonthRenewDate', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('subscriptionDurationType', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscriptionDurationType')
    op.drop_column('team', 'nextMonthRenewDate')
    op.drop_column('team', 'numberOfRenewMonths')
    op.drop_column('team', 'creditRenewDate')
    # ### end Alembic commands ###
