"""adding user foreignb key

Revision ID: 2c342ea2f955
Revises: 9951a6450cfd
Create Date: 2025-05-13 13:13:32.782030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c342ea2f955'
down_revision: Union[str, None] = '9951a6450cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_setter', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment_setter', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'appointment_setter', type_='foreignkey')
    op.drop_column('appointment_setter', 'user_id')
    # ### end Alembic commands ###
