"""active status email

Revision ID: 32714aafd114
Revises: 52f350149578
Create Date: 2025-05-22 12:27:50.048171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32714aafd114'
down_revision: Union[str, None] = '52f350149578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_campaign', sa.Column('is_active', sa.Boolean(), default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_campaign', 'is_active')
    # ### end Alembic commands ###
