"""email model fix

Revision ID: 46cdcd292611
Revises: 5973eb5aac45
Create Date: 2025-05-22 10:18:42.022042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46cdcd292611'
down_revision: Union[str, None] = '5973eb5aac45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_campaign', 'emoji_frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_campaign', sa.Column('emoji_frequency', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
