"""change in appointment setter

Revision ID: 4f93a463977d
Revises: 5efb269b39ba
Create Date: 2025-05-19 14:38:44.574922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f93a463977d'
down_revision: Union[str, None] = '5efb269b39ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_setter', 'reply_max_time')
    op.drop_column('appointment_setter', 'reply_min_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_setter', sa.Column('reply_min_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('appointment_setter', sa.Column('reply_max_time', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
