"""email model

Revision ID: 5973eb5aac45
Revises: 42333448cc14
Create Date: 2025-05-22 10:12:06.270384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5973eb5aac45'
down_revision: Union[str, None] = '42333448cc14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_title', sa.String(), nullable=False),
    sa.Column('campaign_objective', sa.String(), nullable=False),
    sa.Column('main_subject', sa.String(), nullable=False),
    sa.Column('cta_type', sa.String(), nullable=False),
    sa.Column('list_of_target', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('desired_tone', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('send_time_window', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('include_brainai', sa.Boolean(), nullable=True),
    sa.Column('include_branding', sa.Boolean(), nullable=True),
    sa.Column('custom_prompt', sa.String(), nullable=True),
    sa.Column('text_length', sa.String(), nullable=False),
    sa.Column('product_or_service_feature', sa.String(), nullable=False),
    sa.Column('emoji_frequency', sa.Integer(), nullable=False),
    sa.Column('review', sa.Boolean(), nullable=True),
    sa.Column('calender_choosed', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_campaign_id'), 'email_campaign', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_campaign_id'), table_name='email_campaign')
    op.drop_table('email_campaign')
    # ### end Alembic commands ###
