"""user update theme

Revision ID: 5af41fdbdf20
Revises: 652c0ad07298
Create Date: 2025-11-20 12:16:49.268159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5af41fdbdf20'
down_revision: Union[str, None] = '652c0ad07298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwordUpdatedAt', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('theme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme')
    op.drop_column('users', 'passwordUpdatedAt')
    # ### end Alembic commands ###
