"""adding ui brain

Revision ID: 652c0ad07298
Revises: 0df21e7bd75b
Create Date: 2025-11-05 12:46:33.088983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '652c0ad07298'
down_revision: Union[str, None] = '0df21e7bd75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_customer_support_chatbot', sa.Column('use_ai_brain', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smart_customer_support_chatbot', 'use_ai_brain')
    # ### end Alembic commands ###
