"""tiktok

Revision ID: 711da56ba6a0
Revises: 5af41fdbdf20
Create Date: 2025-11-24 10:26:14.209296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '711da56ba6a0'
down_revision: Union[str, None] = '5af41fdbdf20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiktok_connection_details',
    sa.Column('tiktok_id', sa.String(), nullable=False),
    sa.Column('creator_username', sa.String(), nullable=True),
    sa.Column('creator_nickname', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('access_token_expiry_time', sa.DateTime(), nullable=True),
    sa.Column('refresh_token_expiry_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tiktok_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiktok_connection_details')
    # ### end Alembic commands ###
