"""linkedin post

Revision ID: 768f2e7453ac
Revises: 61019715c3d3
Create Date: 2025-07-17 13:50:16.241235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '768f2e7453ac'
down_revision: Union[str, None] = '61019715c3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_content', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('custom_instructions', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_post_id'), 'linkedin_post', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_post_id'), table_name='linkedin_post')
    op.drop_table('linkedin_post')
    # ### end Alembic commands ###
