"""calendar id email

Revision ID: 7c962a7188c2
Revises: 90f52a836775
Create Date: 2025-06-13 13:35:48.648388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c962a7188c2'
down_revision: Union[str, None] = '90f52a836775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_calendar_connection_details', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('google_calendar_connection_details_email_key', 'google_calendar_connection_details', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('google_calendar_connection_details_email_key', 'google_calendar_connection_details', ['email'])
    op.alter_column('google_calendar_connection_details', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
