"""update agent social media field

Revision ID: 7d7aabe67be2
Revises: 8415483b03e5
Create Date: 2025-06-09 11:41:23.398514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d7aabe67be2'
down_revision: Union[str, None] = '8415483b03e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###\
    op.add_column('appointment_setter', sa.Column('platform_unique_id', sa.String(), nullable=False))
    op.drop_constraint('appointment_setter_lead_id_key', 'appointment_setter', type_='unique')
    op.create_unique_constraint(None, 'appointment_setter', ['platform_unique_id'])
    op.drop_column('appointment_setter', 'lead_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_setter', sa.Column('lead_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointment_setter', type_='unique')
    op.create_unique_constraint('appointment_setter_lead_id_key', 'appointment_setter', ['lead_id'])
    op.drop_column('appointment_setter', 'platform_unique_id')
    # ### end Alembic commands ###
