"""phone agent boolean

Revision ID: 82e0af75e300
Revises: ce1a30d03106
Create Date: 2025-06-03 15:03:34.607518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82e0af75e300'
down_revision: Union[str, None] = 'ce1a30d03106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_campaign', sa.Column('tom_engages', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_campaign', 'tom_engages')
    # ### end Alembic commands ###
