"""time update

Revision ID: 856454f9fe07
Revises: 8c06c3876077
Create Date: 2025-05-27 10:52:08.106660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '856454f9fe07'
down_revision: Union[str, None] = '8c06c3876077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_content', sa.Column('scheduled_date', sa.Date(), nullable=False))
    op.add_column('email_content', sa.Column('scheduled_time', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_content', 'scheduled_time')
    op.drop_column('email_content', 'scheduled_date')
    # ### end Alembic commands ###
