"""scheduled content

Revision ID: 8e845f4ad3e1
Revises: 16597323a6ba
Create Date: 2025-07-24 11:59:52.797880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e845f4ad3e1'
down_revision: Union[str, None] = '16597323a6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_unique_id', sa.String(), nullable=False),
    sa.Column('scheduled_type', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('published_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_content_id'), 'scheduled_content', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_content_id'), table_name='scheduled_content')
    op.drop_table('scheduled_content')
    # ### end Alembic commands ###
