"""calendar id

Revision ID: 90f52a836775
Revises: 93177551db6d
Create Date: 2025-06-13 13:26:11.965825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90f52a836775'
down_revision: Union[str, None] = '93177551db6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_setter', sa.Column('calendar_id', sa.String(), nullable=True))
    op.alter_column('google_calendar_connection_details', 'calendar_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('google_calendar_connection_details', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_connection_details', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('google_calendar_connection_details', 'calendar_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('appointment_setter', 'calendar_id')
    # ### end Alembic commands ###
