"""google table update

Revision ID: 93177551db6d
Revises: 7336fa9cbadc
Create Date: 2025-06-13 11:58:43.372827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93177551db6d'
down_revision: Union[str, None] = '7336fa9cbadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_connection_details', sa.Column('timezone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_calendar_connection_details', 'timezone')
    # ### end Alembic commands ###
