"""email model fix

Revision ID: 98a7738dbd24
Revises: 46cdcd292611
Create Date: 2025-05-22 11:09:23.251170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98a7738dbd24'
down_revision: Union[str, None] = '46cdcd292611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_campaign', 'frequency',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_campaign', 'frequency',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    # ### end Alembic commands ###
