"""agent integration track

Revision ID: 9b9d0da6c982
Revises: 9172e601e480
Create Date: 2025-10-22 09:27:10.238348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9d0da6c982'
down_revision: Union[str, None] = '9172e601e480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_integration_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('integration_platform', sa.String(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_integration_track_id'), 'agent_integration_track', ['id'], unique=False)
    op.add_column('customer_support_chats', sa.Column('third_party_lead_id', sa.String(), nullable=True))
    op.add_column('customer_support_chats', sa.Column('connected_platform_id', sa.String(), nullable=True))
    op.add_column('customer_support_chats', sa.Column('platform', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_support_chats', 'platform')
    op.drop_column('customer_support_chats', 'connected_platform_id')
    op.drop_column('customer_support_chats', 'third_party_lead_id')
    op.drop_index(op.f('ix_agent_integration_track_id'), table_name='agent_integration_track')
    op.drop_table('agent_integration_track')
    # ### end Alembic commands ###
