"""updatimg column to integer

Revision ID: a321571a58a8
Revises: 70fa7ebac389
Create Date: 2025-09-04 15:00:22.804597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a321571a58a8'
down_revision: Union[str, None] = '70fa7ebac389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_contact_number', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_record_id'), 'call_record', ['id'], unique=False)
    op.add_column('phone_campaign', sa.Column('target_lists', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_campaign', 'target_lists')
    op.drop_index(op.f('ix_call_record_id'), table_name='call_record')
    op.drop_table('call_record')
    # ### end Alembic commands ###
