"""adding twilio field

Revision ID: a6390364b088
Revises: a321571a58a8
Create Date: 2025-09-08 13:07:47.825972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6390364b088'
down_revision: Union[str, None] = 'a321571a58a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_phone_numbers', sa.Column('twilio_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'agent_phone_numbers', ['twilio_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_phone_numbers', type_='unique')
    op.drop_column('agent_phone_numbers', 'twilio_number')
    # ### end Alembic commands ###
