"""x post model 

Revision ID: b0c714eb3418
Revises: c2a64fca570e
Create Date: 2025-07-18 14:26:52.485386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0c714eb3418'
down_revision: Union[str, None] = 'c2a64fca570e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('x_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_content', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('custom_instructions', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_x_post_id'), 'x_post', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_x_post_id'), table_name='x_post')
    op.drop_table('x_post')
    # ### end Alembic commands ###
