"""avatar

Revision ID: b2617e47aa3f
Revises: 08be3e49b751
Create Date: 2025-10-09 09:32:15.375475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2617e47aa3f'
down_revision: Union[str, None] = '08be3e49b751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smartbot_avatars',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.Column('avatar_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('smart_agent_integration', sa.Column('first_message', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smart_agent_integration', 'first_message')
    op.drop_table('smartbot_avatars')
    # ### end Alembic commands ###
