"""adding platform

Revision ID: b6427cbd10e5
Revises: 9c85b6155f0d
Create Date: 2025-06-12 15:40:12.795046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6427cbd10e5'
down_revision: Union[str, None] = '9c85b6155f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_analytics', sa.Column('platform_unique_id', sa.String(), nullable=True))
    op.drop_column('lead_analytics', 'platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_analytics', sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('lead_analytics', 'platform_unique_id')
    # ### end Alembic commands ###
