"""updation in call table

Revision ID: b9459b6536fd
Revises: e92dab5c08e2
Create Date: 2025-09-11 14:52:28.510036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9459b6536fd'
down_revision: Union[str, None] = 'e92dab5c08e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_record', sa.Column('campaign_name', sa.String(), nullable=True))
    op.add_column('call_record', sa.Column('agent_name', sa.String(), nullable=True))
    op.add_column('call_record', sa.Column('language', sa.String(), nullable=True))
    op.add_column('call_record', sa.Column('voice', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_record', 'voice')
    op.drop_column('call_record', 'language')
    op.drop_column('call_record', 'agent_name')
    op.drop_column('call_record', 'campaign_name')
    # ### end Alembic commands ###
