"""adding agent_type

Revision ID: bce412814d4b
Revises: 1b46d89d7c0d
Create Date: 2025-09-30 08:52:44.745813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bce412814d4b'
down_revision: Union[str, None] = '1b46d89d7c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_chat_history', sa.Column('agent_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_chat_history', 'agent_type')
    # ### end Alembic commands ###
