"""adding user foreign key 

Revision ID: c2a64fca570e
Revises: 768f2e7453ac
Create Date: 2025-07-18 11:13:23.553168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2a64fca570e'
down_revision: Union[str, None] = '768f2e7453ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_post', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'linkedin_post', 'users', ['user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'linkedin_post', type_='foreignkey')
    op.drop_column('linkedin_post', 'user')
    # ### end Alembic commands ###
