"""appointment agent changes

Revision ID: cb729cdae7fc
Revises: 4f93a463977d
Create Date: 2025-05-20 15:15:35.849372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb729cdae7fc'
down_revision: Union[str, None] = '4f93a463977d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_setter', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('appointment_setter', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('appointment_setter', sa.Column('whatsapp_number', sa.String(), nullable=True))
    op.add_column('appointment_setter', sa.Column('prompt', sa.String(), nullable=False))
    op.drop_column('appointment_setter', 'directness')
    op.drop_column('appointment_setter', 'agent_language')
    op.drop_column('appointment_setter', 'webpage_type')
    op.add_column('lead_analytics', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('lead_analytics', sa.Column('updated_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_analytics', 'updated_at')
    op.drop_column('lead_analytics', 'created_at')
    op.add_column('appointment_setter', sa.Column('webpage_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointment_setter', sa.Column('agent_language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointment_setter', sa.Column('directness', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('appointment_setter', 'prompt')
    op.drop_column('appointment_setter', 'whatsapp_number')
    op.drop_column('appointment_setter', 'age')
    op.drop_column('appointment_setter', 'gender')
    # ### end Alembic commands ###
