"""phone agent script

Revision ID: ce1a30d03106
Revises: f79f29f58765
Create Date: 2025-06-03 13:10:59.691270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce1a30d03106'
down_revision: Union[str, None] = 'f79f29f58765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_campaign', sa.Column('country', sa.String(), nullable=False))
    op.add_column('phone_campaign', sa.Column('catch_phrase', sa.String(), nullable=False))
    op.add_column('phone_campaign', sa.Column('call_script', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_campaign', 'call_script')
    op.drop_column('phone_campaign', 'catch_phrase')
    op.drop_column('phone_campaign', 'country')
    # ### end Alembic commands ###
