"""appointment_setter

Revision ID: cf76064be328
Revises: 
Create Date: 2025-05-12 14:50:24.915582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf76064be328'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_setter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('agent_personality', sa.String(), nullable=False),
    sa.Column('agent_language', sa.String(), nullable=True),
    sa.Column('business_description', sa.String(), nullable=False),
    sa.Column('your_business_offer', sa.String(), nullable=False),
    sa.Column('qualification_questions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objective_of_the_agent', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('calendar_choosed', sa.String(), nullable=False),
    sa.Column('reply_min_time', sa.Integer(), nullable=False),
    sa.Column('reply_max_time', sa.Integer(), nullable=False),
    sa.Column('is_followups_enabled', sa.Boolean(), nullable=True),
    sa.Column('follow_up_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emoji_frequency', sa.Integer(), nullable=False),
    sa.Column('directness', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_setter_id'), 'appointment_setter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_setter_id'), table_name='appointment_setter')
    op.drop_table('appointment_setter')
    # ### end Alembic commands ###
