"""updating calls

Revision ID: e374e218ce2a
Revises: 2c342ea2f955
Create Date: 2025-05-13 14:54:17.220558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e374e218ce2a'
down_revision: Union[str, None] = '2c342ea2f955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_setter', sa.Column('webpage_link', sa.String(), nullable=True))
    op.add_column('appointment_setter', sa.Column('webpage_type', sa.String(), nullable=True))
    op.alter_column('appointment_setter', 'calendar_choosed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_setter', 'calendar_choosed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('appointment_setter', 'webpage_type')
    op.drop_column('appointment_setter', 'webpage_link')
    