"""adding call type

Revision ID: e92dab5c08e2
Revises: d11434d7e27a
Create Date: 2025-09-11 14:19:51.487460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e92dab5c08e2'
down_revision: Union[str, None] = 'd11434d7e27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_record', sa.Column('call_type', sa.String(), nullable=True))
    op.add_column('call_record', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('phone_campaign', sa.Column('campaign_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_campaign', 'campaign_type')
    op.drop_column('call_record', 'user_id')
    op.drop_column('call_record', 'call_type')
    # ### end Alembic commands ###
