"""lead_tables

Revision ID: ee236a1a3418
Revises: b04601fe0fac
Create Date: 2025-05-18 11:13:23.066985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee236a1a3418'
down_revision: Union[str, None] = 'b04601fe0fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_agent_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_index(op.f('ix_appointment_agent_leads_id'), 'appointment_agent_leads', ['id'], unique=False)
    op.create_table('lead_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_history', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('agent_is_enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['appointment_setter.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['appointment_agent_leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_lead_analytics_id'), 'lead_analytics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_analytics_id'), table_name='lead_analytics')
    op.drop_table('lead_analytics')
    op.drop_index(op.f('ix_appointment_agent_leads_id'), table_name='appointment_agent_leads')
    op.drop_table('appointment_agent_leads')
    # ### end Alembic commands ###
