"""phone agent created at

Revision ID: f79f29f58765
Revises: 0fb8c8560e6c
Create Date: 2025-06-03 13:00:46.218770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f79f29f58765'
down_revision: Union[str, None] = '0fb8c8560e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_campaign', sa.Column('campaign_name', sa.String(), nullable=False))
    op.add_column('phone_campaign', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_campaign', 'created_at')
    op.drop_column('phone_campaign', 'campaign_name')
    # ### end Alembic commands ###
