"""updating calls again

Revision ID: f9ce05bf531e
Revises: e374e218ce2a
Create Date: 2025-05-13 15:16:53.224166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9ce05bf531e'
down_revision: Union[str, None] = 'e374e218ce2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_setter', 'objective_of_the_agent',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_setter', 'objective_of_the_agent',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)