"""coo agent

Revision ID: fc7eae9e27f2
Revises: 4d6e18f1029f
Create Date: 2025-06-25 09:40:33.763934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc7eae9e27f2'
down_revision: Union[str, None] = '4d6e18f1029f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coo_chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('chat_history', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_coo_chat_history_id'), 'coo_chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_seo_chat_history_id'), 'seo_chat_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_chat_history_id'), table_name='seo_chat_history')
    op.drop_index(op.f('ix_coo_chat_history_id'), table_name='coo_chat_history')
    op.drop_table('coo_chat_history')
    # ### end Alembic commands ###
