"""initial migration

Revision ID: ff0a74321536
Revises: 
Create Date: 2025-07-07 13:46:11.178252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff0a74321536'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_agent_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_index(op.f('ix_appointment_agent_leads_id'), 'appointment_agent_leads', ['id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('phoneNumber', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('subscriptionType', sa.String(length=20), nullable=True),
    sa.Column('countryCode', sa.String(length=20), nullable=True),
    sa.Column('paymentId', sa.String(length=100), nullable=True),
    sa.Column('activeProfile', sa.Boolean(), nullable=True),
    sa.Column('isProfileComplete', sa.Boolean(), nullable=True),
    sa.Column('stripeCustomerId', sa.String(length=50), nullable=True),
    sa.Column('subscriptionStatus', sa.String(length=50), nullable=True),
    sa.Column('subscriptionId', sa.String(length=100), nullable=True),
    sa.Column('refreshToken', sa.String(length=255), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('subscriptionEndDate', sa.DateTime(), nullable=True),
    sa.Column('subscriptionStartDate', sa.DateTime(), nullable=True),
    sa.Column('subscriptionUpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('account_chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('chat_history', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_account_chat_history_id'), 'account_chat_history', ['id'], unique=False)
    op.create_table('agent_phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('number_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_agent_phone_numbers_id'), 'agent_phone_numbers', ['id'], unique=False)
    op.create_table('appointment_setter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('agent_personality', sa.String(), nullable=False),
    sa.Column('agent_language', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('business_description', sa.String(), nullable=False),
    sa.Column('your_business_offer', sa.String(), nullable=False),
    sa.Column('qualification_questions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objective_of_the_agent', sa.String(), nullable=False),
    sa.Column('calendar_choosed', sa.String(), nullable=True),
    sa.Column('calendar_id', sa.String(), nullable=True),
    sa.Column('webpage_link', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('platform_unique_id', sa.String(), nullable=False),
    sa.Column('is_followups_enabled', sa.Boolean(), nullable=True),
    sa.Column('follow_up_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emoji_frequency', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_unique_id')
    )
    op.create_index(op.f('ix_appointment_setter_id'), 'appointment_setter', ['id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('post_type', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('video_duration', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('post_status', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('media_urls', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_table('content_creation_chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('chat_history', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_content_creation_chat_history_id'), 'content_creation_chat_history', ['id'], unique=False)
    op.create_table('coo_chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('chat_history', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_coo_chat_history_id'), 'coo_chat_history', ['id'], unique=False)
    op.create_table('email_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_title', sa.String(), nullable=False),
    sa.Column('campaign_objective', sa.String(), nullable=False),
    sa.Column('main_subject', sa.String(), nullable=False),
    sa.Column('cta_type', sa.String(), nullable=False),
    sa.Column('list_of_target', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('desired_tone', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('send_time_window', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('include_brainai', sa.Boolean(), nullable=True),
    sa.Column('include_branding', sa.Boolean(), nullable=True),
    sa.Column('custom_prompt', sa.String(), nullable=True),
    sa.Column('text_length', sa.String(), nullable=False),
    sa.Column('product_or_service_feature', sa.String(), nullable=False),
    sa.Column('review', sa.Boolean(), nullable=True),
    sa.Column('calender_choosed', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_campaign_id'), 'email_campaign', ['id'], unique=False)
    op.create_table('google_calendar_connection_details',
    sa.Column('calendar_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    op.create_table('hr_chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('chat_history', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_hr_chat_history_id'), 'hr_chat_history', ['id'], unique=False)
    op.create_table('instagram_connection_details',
    sa.Column('instagram_user_id', sa.String(), nullable=False),
    sa.Column('instagram_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instagram_user_id', 'instagram_id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.create_table('phone_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('voice', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_agent_id'), 'phone_agent', ['id'], unique=False)
    op.create_table('seo_chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('chat_history', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_seo_chat_history_id'), 'seo_chat_history', ['id'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('numberOfTeamMembers', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('paymentId', sa.String(length=100), nullable=False),
    sa.Column('amountPaid', sa.Float(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paymentMethod', sa.String(length=50), nullable=True),
    sa.Column('subscriptionType', sa.String(length=20), nullable=True),
    sa.Column('receiptUrl', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('transactionDate', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp_connection_details',
    sa.Column('whatsapp_business_id', sa.String(), nullable=False),
    sa.Column('whatsapp_phone_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('whatsapp_phone_id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('businessName', sa.String(), nullable=True),
    sa.Column('companyName', sa.String(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created', sa.String(), nullable=True),
    sa.Column('lastActivity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('additionalEmails', sa.String(), nullable=True),
    sa.Column('additionalPhones', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('email_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_content_id'), 'email_content', ['id'], unique=False)
    op.create_table('invite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('teamId', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('lead_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_history', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('agent_is_enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('platform_unique_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['appointment_setter.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['appointment_agent_leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_lead_analytics_id'), 'lead_analytics', ['id'], unique=False)
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listName', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lists_id'), 'lists', ['id'], unique=False)
    op.create_table('phone_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('voice', sa.String(), nullable=False),
    sa.Column('choose_calendar', sa.String(), nullable=True),
    sa.Column('max_call_time', sa.Integer(), nullable=True),
    sa.Column('target_lists', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('catch_phrase', sa.String(), nullable=False),
    sa.Column('call_script', sa.String(), nullable=False),
    sa.Column('tom_engages', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('agent', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent'], ['phone_agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_campaign_id'), 'phone_campaign', ['id'], unique=False)
    op.create_table('teammembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('teamId', sa.String(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contactid', sa.Integer(), nullable=True),
    sa.Column('lists_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contactid'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lists_id'], ['lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_lists_id'), 'contact_lists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_lists_id'), table_name='contact_lists')
    op.drop_table('contact_lists')
    op.drop_table('teammembers')
    op.drop_index(op.f('ix_phone_campaign_id'), table_name='phone_campaign')
    op.drop_table('phone_campaign')
    op.drop_index(op.f('ix_lists_id'), table_name='lists')
    op.drop_table('lists')
    op.drop_index(op.f('ix_lead_analytics_id'), table_name='lead_analytics')
    op.drop_table('lead_analytics')
    op.drop_table('invite_tokens')
    op.drop_index(op.f('ix_email_content_id'), table_name='email_content')
    op.drop_table('email_content')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('whatsapp_connection_details')
    op.drop_table('transaction_history')
    op.drop_table('team')
    op.drop_index(op.f('ix_seo_chat_history_id'), table_name='seo_chat_history')
    op.drop_table('seo_chat_history')
    op.drop_index(op.f('ix_phone_agent_id'), table_name='phone_agent')
    op.drop_table('phone_agent')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_table('instagram_connection_details')
    op.drop_index(op.f('ix_hr_chat_history_id'), table_name='hr_chat_history')
    op.drop_table('hr_chat_history')
    op.drop_table('google_calendar_connection_details')
    op.drop_index(op.f('ix_email_campaign_id'), table_name='email_campaign')
    op.drop_table('email_campaign')
    op.drop_index(op.f('ix_coo_chat_history_id'), table_name='coo_chat_history')
    op.drop_table('coo_chat_history')
    op.drop_index(op.f('ix_content_creation_chat_history_id'), table_name='content_creation_chat_history')
    op.drop_table('content_creation_chat_history')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_appointment_setter_id'), table_name='appointment_setter')
    op.drop_table('appointment_setter')
    op.drop_index(op.f('ix_agent_phone_numbers_id'), table_name='agent_phone_numbers')
    op.drop_table('agent_phone_numbers')
    op.drop_index(op.f('ix_account_chat_history_id'), table_name='account_chat_history')
    op.drop_table('account_chat_history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_appointment_agent_leads_id'), table_name='appointment_agent_leads')
    op.drop_table('appointment_agent_leads')
    # ### end Alembic commands ###
